# Переменные окружения для кластера Kafka
x-connect: &kafka-common-env
  ALLOW_PLAINTEXT_LISTENER: yes
  CLUSTER_ID: practicum
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"

  # === КОНФИГУРАЦИЯ АРХИТЕКТУРЫ KRaft ===
  # 1. Включение KRaft-режима
  KAFKA_ENABLE_KRAFT: yes
  # 2. Имена слушателей для контроллера
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  # 3. Список участников кворума контроллеров
  KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
  # 4. Роли узлов: и брокер, и контроллер
  KAFKA_PROCESS_ROLES: broker,controller

services:
  # Kafka-брокер 1/3
  kafka-0:
    container_name: kafka-0
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
    networks:
      kafka-connect-network:

  # Kafka-брокер 2/3
  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9095:9095"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
    networks:
      kafka-connect-network:

  # Kafka-брокер 3/3
  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    restart: always
    ports:
      - "9096:9096"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    networks:
      kafka-connect-network:

  # Веб-интерфейс для управления и мониторинга Kafka
  ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    ports:
    - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      KAFKA_CLUSTERS_0_NAME: kraft
    networks:
      kafka-connect-network:

networks:
  kafka-connect-network:
    name: kafka-connect-network
